name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Rename atlyss_save_editor.html to index.html
    - name: Rename atlyss_save_editor.html to index.html
      run: mv atlyss_save_editor.html index.html

    # Step 3: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust if your files are in a subdirectory
